version: '3.8'
services:
  fortune-wheel:
    build: .
    image: kalugin66/fortune-wheel
    container_name: fortune-wheel
    ports:
      - "3005:3000"
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
#docker-compose up -d --build
